####################
# Page Settings
####################
baseurl = "localhost:1313"
languageCode = "de-DE"
title = "Calyrium.org"
copyright = "Copyright 2016 calyrium.org"

####################
# System Settings
####################
theme =         "calyrium"
canonifyurls =  true
contentdir =    "content"
publishdir =    "public"
watch =         true

#####################
# Syntax Highlighting
#####################
# color-codes for highlighting derived from this style
pygmentsStyle =         "friendly"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses = false
PygmentsCodeFences = false

####################
# Setup Menu
####################
[[menu.main]]
   name = "Blog"
   weight = -110
   identifier = "blog"
   url = "/blog/"

[indexes]
category =      "categories"
tag =           "tags"


[Params]
AuthorName =    "kreativmonkey"
#cover =        "/images/background-cover.jpg"
#logo =         "/img/logo-1.jpg"

[Author]
  name = 	"Sebastian Preisner"
  image =	"/images/profile.jpg"
  email = 	"admin@calyrium.org"
  facebook = 	"liveras"
  github = 	"kreativmonkey"
  #bitbucket =	"floch"
  twitter = 	"kreativmonkey"
  flickr =  	"kreativmonkey"
  #linkedin = 	"pub/username/X/YYY/ZZZ"
  #stackoverflow = "XXXXXXX/username"
  #soundcloud = "username"
  #wikipedia = 	"username"
