####################
# Page Settings
####################
baseurl = "https://hugo.calyrium.org/"
languageCode = "de-DE"
title = "Calyrium.org"
author = "Kreativmonkey"
copyright = "Copyright 2016 Kreativmonkey"

###################
## Link Settings
###################
#[permalinks]
#  post = "/:year/:month/:title/"
#  page = "/:title/"

####################
# System Settings
####################
theme =         "calyrium"
canonifyurls =  true
contentdir =    "content"
publishdir =    "public"
watch =         true

#####################
# Syntax Highlighting
#####################
# color-codes for highlighting derived from this style
pygmentsStyle =         "friendly"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses = false
PygmentsCodeFences = false

####################
# Setup Menu
####################
[[menu.main]]
   name = "Blog"
   weight = -110
   identifier = "blog"
   url = "/blog/"

[indexes]
category =      "categories"
tag =           "tags"

[Params]
AuthorName =    "kreativmonkey"
github =        "kreativmonkey"
youtube =       "UCbwr9WE1ksW6XttEOuEiTeQ"
#bitbucket =    "floch"
flickr =        "kreativmonkey"
twitter =       "kreativmonkey"
facebook =      "liveras"
#email =        "mail@fredrikloch.me"
description =   ""
#cv =           "/pages/cv"
#legalnotice =  "/pages/legal-notice"
#muut =         "fredrikloch"
#linkedin =     "fredrikloch"
#cover =        "/images/background-cover.jpg"
#logo =         "/img/logo-1.jpg"

